# Numpy - Array Manipulation
---

## 1. Reshape Array

### 1.1 `reshape()` vs `resize()`
- Change dimension of the existing array

In [1]:
import numpy as np

In [2]:
x = np.arange(1, 13)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
# Result of reshaping is a view of the original array
reshape_x = x.reshape(6, 2)
reshape_x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [4]:
reshape_x[0, 0] = 11
print(reshape_x)
print(x)

[[11  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[11  2  3  4  5  6  7  8  9 10 11 12]


In [5]:
print(reshape_x.base)
print(reshape_x.base is x)

[11  2  3  4  5  6  7  8  9 10 11 12]
True


#### 1.1.1 Different from using `resize()` 
- `numpy.resize()` returns the **new** resized ndarray **(Not <u>view</u>)**

In [6]:
resize_x = np.resize(x, (6, 2))
print(resize_x)

[[11  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [7]:
print(resize_x.base)
print(resize_x.base is x)

[11  2  3  4  5  6  7  8  9 10 11 12]
False


### 1.2 `flatten()`
- Convert a multidimensional array into a 1D array

In [8]:
resize_x.flatten()

array([11,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 1.3 `transpose()`
- Reverse the axes of an array

In [9]:
print(reshape_x)
print(reshape_x.transpose())
print(reshape_x.T)

[[11  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[11  3  5  7  9 11]
 [ 2  4  6  8 10 12]]
[[11  3  5  7  9 11]
 [ 2  4  6  8 10 12]]


## 2. Join Array

### 2.1 `concatenate()`
- Concatenate **array elements** along their corresponding and existing axis.

In [10]:
x = np.arange(0, 6).reshape(2, 3)
print('x:\n', x, '\n')
y = np.arange(6, 12).reshape(2, 3)
print('y:\n', y, '\n')

# Default axis is 0
con_ax0 = np.concatenate((x, y))
print('concatenate with axis = 0', '\n')
print(con_ax0, '\n')

con_ax1 = np.concatenate((x, y), axis = 1)
print('concatenate with axis = 1', '\n')
print(con_ax1, '\n')

x:
 [[0 1 2]
 [3 4 5]] 

y:
 [[ 6  7  8]
 [ 9 10 11]] 

concatenate with axis = 0 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

concatenate with axis = 1 

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]] 



### 2.2 `stack()`
- Stack (not concatenate) **arrays** on the specified new axis.

In [11]:
print('x:\n', x, '\n')
print('x.shape =', x.shape, '\n')
print('y:\n', y, '\n')
print('y.shape =', y.shape, '\n')

x:
 [[0 1 2]
 [3 4 5]] 

x.shape = (2, 3) 

y:
 [[ 6  7  8]
 [ 9 10 11]] 

y.shape = (2, 3) 



In [12]:
st_ax0 = np.stack((x, y))
st_ax1 = np.stack((x, y), axis = 1)

print('stack with axis = 0:\n', st_ax0, '\n')
print('st_ax0.shape =', st_ax0.shape, '\n')
print('stack with axis = 1:\n', st_ax1, '\n')
print('st_ax1.shape =', st_ax1.shape, '\n')

stack with axis = 0:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] 

st_ax0.shape = (2, 2, 3) 

stack with axis = 1:
 [[[ 0  1  2]
  [ 6  7  8]]

 [[ 3  4  5]
  [ 9 10 11]]] 

st_ax1.shape = (2, 2, 3) 



## 3. Add/Remove Array Elements

### 3.1 `insert()`
- Insert elements at the specified index.

In [13]:
x = np.arange(0, 12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
np.insert(x, 3, 88)

array([ 0,  1,  2, 88,  3,  4,  5,  6,  7,  8,  9, 10, 11])

- Insert without the **specified axis** -- array will be **flattened** first.

In [15]:
rx = x.reshape(4, 3)
rx

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
np.insert(rx, 1, 88)

array([ 0, 88,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

- Insert with the **specified axis**.

In [17]:
np.insert(rx, 1, 88, axis = 0)

array([[ 0,  1,  2],
       [88, 88, 88],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
np.insert(rx, 1, 88, axis = 1)

array([[ 0, 88,  1,  2],
       [ 3, 88,  4,  5],
       [ 6, 88,  7,  8],
       [ 9, 88, 10, 11]])

### 3.2 `delete()`
- Delete elements at the specified index and axis.
- Similar to `insert()`, the array will be **flattened** first if the **specified axis** is not given.

In [19]:
x = np.arange(0, 12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
np.delete(x, 1)

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
rx = x.reshape(4, 3)
rx

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
np.delete(rx, 1, axis = 0)

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
np.delete(rx, 1, axis = 1)

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

In [24]:
np.delete(rx, 1)

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])