# Numpy - Basic Operations
---

In [1]:
import numpy as np

## 1. Vectorization and Broadcasting

### 1.1 NumPy operations on arrays with the **same shape**

In [2]:
x = np.arange(0, 5)
print('x:\n', x, '\n')
print('x.shape =', x.shape, '\n')

y = np.arange(5, 10)
print('y:\n', y, '\n')
print('y.shape =', y.shape, '\n')

# Do only vectorization
print('x + y:\n', x + y, '\n')

x:
 [0 1 2 3 4] 

x.shape = (5,) 

y:
 [5 6 7 8 9] 

y.shape = (5,) 

x + y:
 [ 5  7  9 11 13] 



### 1.2 NumPy operations on arrays with the **diffrent shapes**

In [3]:
%%script python --no-raise-error

z = np.arange(10, 13)
print('z:\n', z, '\n')
print('z.shape =', z.shape, '\n')

# ValueError: operands could not be broadcast together with shapes (5,) (3,) 
print('x + z:\n', x + z, '\n')

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'np' is not defined


### 1.3 NumPy operations on arrays with **compatible dimensions**
#### 1.3.1 with 1-D arrays

In [4]:
x = np.arange(0, 5)
print('x:\n', x, '\n')
print('x.shape =', x.shape, '\n')

y = np.array([10])
print('y:\n', y, '\n')
print('y.shape =', y.shape, '\n')

# Do vectorization and broadcasting
print('x * y:\n', x * y, '\n')

x:
 [0 1 2 3 4] 

x.shape = (5,) 

y:
 [10] 

y.shape = (1,) 

x * y:
 [ 0 10 20 30 40] 



#### 1.3.2 with 2-D arrays

In [5]:
x = np.arange(0, 12).reshape(2, 6)
print('x:\n', x, '\n')
print('x.shape =', x.shape, '\n')

y = np.arange(0, 6).reshape(1, 6)
print('y:\n', y, '\n')
print('y.shape =', y.shape, '\n')

# Do vectorization and broadcasting
print('x * y:\n', x * y, '\n')

x:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 

x.shape = (2, 6) 

y:
 [[0 1 2 3 4 5]] 

y.shape = (1, 6) 

x * y:
 [[ 0  1  4  9 16 25]
 [ 0  7 16 27 40 55]] 



#### 1.3.3 with 3-D arrays

In [6]:
x = np.arange(0, 18).reshape(2, 3, 3)
print('x:\n', x, '\n')
print('x.shape =', x.shape, '\n')

y = np.arange(0, 6).reshape(2, 3, 1)
print('y:\n', y, '\n')
print('y.shape =', y.shape, '\n')

# Do vectorization and broadcasting
print('x * y:\n', x * y, '\n')

x:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]] 

x.shape = (2, 3, 3) 

y:
 [[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] 

y.shape = (2, 3, 1) 

x * y:
 [[[ 0  0  0]
  [ 3  4  5]
  [12 14 16]]

 [[27 30 33]
  [48 52 56]
  [75 80 85]]] 



#### 1.3.4 two arrays with **different number of dimensions**

In [7]:
x = np.arange(0, 6).reshape(2, 3)
print('x:\n', x, '\n')
print('x.shape =', x.shape, '\n')

y = np.arange(0, 3)
print('y:\n', y, '\n')
print('y.shape =', y.shape, '\n')

# Do vectorization and broadcasting
print('x * y:\n', x * y, '\n')

x:
 [[0 1 2]
 [3 4 5]] 

x.shape = (2, 3) 

y:
 [0 1 2] 

y.shape = (3,) 

x * y:
 [[ 0  1  4]
 [ 0  4 10]] 



In [8]:
x = np.arange(0, 15).reshape(3, 5)
print('x:\n', x, '\n')
print('x.shape =', x.shape, '\n')

y = np.arange(0, 3).reshape(3, 1)
print('y:\n', y, '\n')
print('y.shape =', y.shape, '\n')

# Do vectorization and broadcasting
print('x * y:\n', x * y, '\n')

x:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

x.shape = (3, 5) 

y:
 [[0]
 [1]
 [2]] 

y.shape = (3, 1) 

x * y:
 [[ 0  0  0  0  0]
 [ 5  6  7  8  9]
 [20 22 24 26 28]] 



## 2. A Look at Math Operations
![Alt text](pictures/Dataset.png)

In [9]:
scores = np.array([
  [70, 75, 80],
  [80, 75, 70],
  [80, 85, 90],
  [90, 85, 80],
  [70, 80, 90],
])
print(scores)

[[70 75 80]
 [80 75 70]
 [80 85 90]
 [90 85 80]
 [70 80 90]]


In [10]:
print(np.min(scores, axis = 0))
print(np.min(scores, axis = 1))

[70 75 70]
[70 70 80 80 70]


In [11]:
print(np.max(scores, axis = 0))
print(np.max(scores, axis = 1))

[90 85 90]
[80 80 90 90 90]


In [12]:
print(np.mean(scores, axis = 0))
print(np.mean(scores, axis = 1))

[78. 80. 82.]
[75. 75. 85. 85. 80.]


In [13]:
print(np.sum(scores, axis = 1))

[225 225 255 255 240]


In [14]:
# Linear Regression
x = np.arange(-5, 5)
print('x: ', x)
y = 2 * x + 10
print('y: ',y)

x:  [-5 -4 -3 -2 -1  0  1  2  3  4]
y:  [ 0  2  4  6  8 10 12 14 16 18]


## 3. Sorting and Filtering/Searching

- Use `numpy.sort()` -> Return a sorted copy of an array

`numpy.sort(a, axis=- 1, kind=None, order=None)`

In [15]:
scores

array([[70, 75, 80],
       [80, 75, 70],
       [80, 85, 90],
       [90, 85, 80],
       [70, 80, 90]])

In [16]:
# Ascending sort
print(np.sort(scores, axis = 0))
print('\n')
print(np.sort(scores, axis = 1))

[[70 75 70]
 [70 75 80]
 [80 80 80]
 [80 85 90]
 [90 85 90]]


[[70 75 80]
 [70 75 80]
 [80 85 90]
 [80 85 90]
 [70 80 90]]


In [17]:
# Descending sort
print(-(np.sort(-scores, axis = 0)))
print('\n')
print(-(np.sort(-scores, axis = 1)))

[[90 85 90]
 [80 85 90]
 [80 80 80]
 [70 75 80]
 [70 75 70]]


[[80 75 70]
 [80 75 70]
 [90 85 80]
 [90 85 80]
 [90 80 70]]


- Sort by **structure field** - order by *field_name*

In [18]:
# Define customer structure dtype
customer_dtype = np.dtype([('cid', np.str_, 10), ('name', str, 30), ('age', np.int8)])

# Customer records
customer_list = [('C100', 'David', 25), ('C200', 'Phil', 30), ('C300', 'Steve', 35)]

# Create customer_dtype ndarray
customers = np.array(customer_list, dtype = customer_dtype)

print(customers)

[('C100', 'David', 25) ('C200', 'Phil', 30) ('C300', 'Steve', 35)]


In [19]:
# Ascending sort
print(np.sort(customers, order = 'age'))

[('C100', 'David', 25) ('C200', 'Phil', 30) ('C300', 'Steve', 35)]


In [20]:
# Descending sort
print(np.sort(customers, order = 'age')[::-1])

[('C300', 'Steve', 35) ('C200', 'Phil', 30) ('C100', 'David', 25)]
