# Numpy - Basic Operations
---

In [1]:
import numpy as np

## 1. Vectorization and Broadcasting

### 1.1 NumPy operations on arrays with the **same shape**

In [2]:
x = np.arange(0, 5)
print('x:\n', x, '\n')
print('x.shape =', x.shape, '\n')

y = np.arange(5, 10)
print('y:\n', y, '\n')
print('y.shape =', y.shape, '\n')

# Do only vectorization
print('x + y:\n', x + y, '\n')

x:
 [0 1 2 3 4] 

x.shape = (5,) 

y:
 [5 6 7 8 9] 

y.shape = (5,) 

x + y:
 [ 5  7  9 11 13] 



### 1.2 NumPy operations on arrays with the **diffrent shapes**

In [3]:
z = np.arange(10, 13)
print('z:\n', z, '\n')
print('z.shape =', z.shape, '\n')

# ValueError: operands could not be broadcast together with shapes (5,) (3,) 
print('x + z:\n', x + z, '\n')

z:
 [10 11 12] 

z.shape = (3,) 



ValueError: operands could not be broadcast together with shapes (5,) (3,) 

### 1.3 NumPy operations on arrays with **compatible dimensions**
#### 1.3.1 with 1-D arrays

In [ ]:
x = np.arange(0, 5)
print('x:\n', x, '\n')
print('x.shape =', x.shape, '\n')

y = np.array([10])
print('y:\n', y, '\n')
print('y.shape =', y.shape, '\n')

# Do vectorization and broadcasting
print('x * y:\n', x * y, '\n')

x:
 [0 1 2 3 4] 

x.shape = (5,) 

y:
 [10] 

y.shape = (1,) 

x * y:
 [ 0 10 20 30 40] 



#### 1.3.2 with 2-D arrays

In [ ]:
x = np.arange(0, 12).reshape(2, 6)
print('x:\n', x, '\n')
print('x.shape =', x.shape, '\n')

y = np.arange(0, 6).reshape(1, 6)
print('y:\n', y, '\n')
print('y.shape =', y.shape, '\n')

# Do vectorization and broadcasting
print('x * y:\n', x * y, '\n')

x:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 

x.shape = (2, 6) 

y:
 [[0 1 2 3 4 5]] 

y.shape = (1, 6) 

x * y:
 [[ 0  1  4  9 16 25]
 [ 0  7 16 27 40 55]] 



#### 1.3.3 with 3-D arrays

In [ ]:
x = np.arange(0, 18).reshape(2, 3, 3)
print('x:\n', x, '\n')
print('x.shape =', x.shape, '\n')

y = np.arange(0, 6).reshape(2, 3, 1)
print('y:\n', y, '\n')
print('y.shape =', y.shape, '\n')

# Do vectorization and broadcasting
print('x * y:\n', x * y, '\n')

x:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]] 

x.shape = (2, 3, 3) 

y:
 [[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] 

y.shape = (2, 3, 1) 

x * y:
 [[[ 0  0  0]
  [ 3  4  5]
  [12 14 16]]

 [[27 30 33]
  [48 52 56]
  [75 80 85]]] 



#### 1.3.4 two arrays with **different number of dimensions**

In [4]:
x = np.arange(0, 6).reshape(2, 3)
print('x:\n', x, '\n')
print('x.shape =', x.shape, '\n')

y = np.arange(0, 3)
print('y:\n', y, '\n')
print('y.shape =', y.shape, '\n')

# Do vectorization and broadcasting
print('x * y:\n', x * y, '\n')

x:
 [[0 1 2]
 [3 4 5]] 

x.shape = (2, 3) 

y:
 [0 1 2] 

y.shape = (3,) 

x * y:
 [[ 0  1  4]
 [ 0  4 10]] 



In [5]:
x = np.arange(0, 15).reshape(3, 5)
print('x:\n', x, '\n')
print('x.shape =', x.shape, '\n')

y = np.arange(0, 3)
print('y:\n', y, '\n')
print('y.shape =', y.shape, '\n')

# Do vectorization and broadcasting
print('x * y:\n', x * y, '\n')

x:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

x.shape = (3, 5) 

y:
 [0 1 2] 

y.shape = (3,) 



ValueError: operands could not be broadcast together with shapes (3,5) (3,) 