# Numpy - Basic Operations
---

In [1]:
import numpy as np

## 1. Vectorization and Broadcasting

### 1.1 NumPy operations on arrays with the **same shape**

In [2]:
x = np.arange(0, 5)
print('x:\n', x, '\n')
print('x.shape =', x.shape, '\n')

y = np.arange(5, 10)
print('y:\n', y, '\n')
print('y.shape =', y.shape, '\n')

# Do only vectorization
print('x + y:\n', x + y, '\n')

x:
 [0 1 2 3 4] 

x.shape = (5,) 

y:
 [5 6 7 8 9] 

y.shape = (5,) 

x + y:
 [ 5  7  9 11 13] 



### 1.2 NumPy operations on arrays with the **diffrent shapes**

In [3]:
z = np.arange(10, 13)
print('z:\n', z, '\n')
print('z.shape =', z.shape, '\n')

# ValueError: operands could not be broadcast together with shapes (5,) (3,) 
print('x + z:\n', x + z, '\n')

z:
 [10 11 12] 

z.shape = (3,) 



ValueError: operands could not be broadcast together with shapes (5,) (3,) 

### 1.3 NumPy operations on arrays with **compatible dimensions**
#### 1.3.1 with 1-D arrays

In [ ]:
x = np.arange(0, 5)
print('x:\n', x, '\n')
print('x.shape =', x.shape, '\n')

y = np.array([10])
print('y:\n', y, '\n')
print('y.shape =', y.shape, '\n')

# Do vectorization and broadcasting
print('x * y:\n', x * y, '\n')

#### 1.3.2 with 2-D arrays

In [ ]:
x = np.arange(0, 12).reshape(2, 6)
print('x:\n', x, '\n')
print('x.shape =', x.shape, '\n')

y = np.arange(0, 6).reshape(1, 6)
print('y:\n', y, '\n')
print('y.shape =', y.shape, '\n')

# Do vectorization and broadcasting
print('x * y:\n', x * y, '\n')

#### 1.3.3 with 3-D arrays

In [ ]:
x = np.arange(0, 18).reshape(2, 3, 3)
print('x:\n', x, '\n')
print('x.shape =', x.shape, '\n')

y = np.arange(0, 6).reshape(2, 3, 1)
print('y:\n', y, '\n')
print('y.shape =', y.shape, '\n')

# Do vectorization and broadcasting
print('x * y:\n', x * y, '\n')

#### 1.3.4 two arrays with **different number of dimensions**

In [ ]:
x = np.arange(0, 6).reshape(2, 3)
print('x:\n', x, '\n')
print('x.shape =', x.shape, '\n')

y = np.arange(0, 3)
print('y:\n', y, '\n')
print('y.shape =', y.shape, '\n')

# Do vectorization and broadcasting
print('x * y:\n', x * y, '\n')

In [ ]:
x = np.arange(0, 15).reshape(3, 5)
print('x:\n', x, '\n')
print('x.shape =', x.shape, '\n')

y = np.arange(0, 3)
print('y:\n', y, '\n')
print('y.shape =', y.shape, '\n')

# Do vectorization and broadcasting
print('x * y:\n', x * y, '\n')

## 2. A Look at Math Operations
![Alt text](Dataset.png)

In [ ]:
scores = np.array([
  [70, 75, 80],
  [80, 75, 70],
  [80, 85, 90],
  [90, 85, 80],
  [70, 80, 90],
])
print(scores)

In [ ]:
print(np.min(scores, axis = 0))
print(np.min(scores, axis = 1))

In [ ]:
print(np.max(scores, axis = 0))
print(np.max(scores, axis = 1))

In [ ]:
print(np.mean(scores, axis = 0))
print(np.mean(scores, axis = 1))

In [ ]:
print(np.sum(scores, axis = 1))

In [ ]:
# Linear Regression
x = np.arange(-5, 5)
print('x: ', x)
y = 2 * x + 10
print('y: ',y)

## 3. Sorting and Filtering/Searching

- Use `numpy.sort()` -> Return a sorted copy of an array

`numpy.sort(a, axis=- 1, kind=None, order=None)`

In [ ]:
scores

In [ ]:
# Ascending sort
print(np.sort(scores, axis = 0))
print('\n')
print(np.sort(scores, axis = 1))

In [ ]:
# Descending sort
print(-(np.sort(-scores, axis = 0)))
print('\n')
print(-(np.sort(-scores, axis = 1)))

- Sort by **structure field** - order by *field_name*

In [ ]:
# Define customer structure dtype
customer_dtype = np.dtype([('cid', np.str_, 10), ('name', str, 30), ('age', np.int8)])

# Customer records
customer_list = [('C100', 'David', 25), ('C200', 'Phil', 30), ('C300', 'Steve', 35)]

# Create customer_dtype ndarray
customers = np.array(customer_list, dtype = customer_dtype)

print(customers)

In [ ]:
# Ascending sort
print(np.sort(customers, order = 'age'))

In [ ]:
# Descending sort
print(np.sort(customers, order = 'age')[::-1])