# NumPy - Random Sampling
---

In [1]:
import numpy as np
from numpy.random import default_rng

## 1. Random Number Generator

---

### 1.1 Recent NumPy Versions

- The new approach to generate random numbers in NumPy with better statistical properties.

In [2]:
# Create object of default random number generator
rng = default_rng()

# Random 5 float numbers from 0.0 to 1.0
rng.random(5)

array([0.59755542, 0.89689979, 0.51670438, 0.56021853, 0.62138878])

### 1.2 Legacy Versions

In [3]:
from numpy import random

random.rand(5)

array([0.88646157, 0.46982222, 0.82923406, 0.25099011, 0.32233717])

### 1.3 Seed Number
- Use to **control** the **sequence** of **random state** of **random number generator**

In [4]:
# seed = 2021
rng = default_rng(2021)

rng.random(5)

array([0.75694783, 0.94138187, 0.59246304, 0.31884171, 0.62607384])

In [5]:
rng = default_rng(2021)

rng.random(5)

array([0.75694783, 0.94138187, 0.59246304, 0.31884171, 0.62607384])

## 2. Basic Random Numbers

----

### 2.1 Random Integer

In [6]:
rng = default_rng()

# endpoint = True -> for include 10 to range
rng.integers(low = 0, high = 10, endpoint = True, size = 5)

array([ 4,  6, 10, 10,  9], dtype=int64)

### 2.2 Random Float Numbers

- Random float numbers from `[0.0, 1.0)`

In [7]:
rng.random(5)

array([0.20521256, 0.06916712, 0.0619868 , 0.16452418, 0.24022188])

- **Reshape** ndarray after sampling

In [8]:
rng.random(10).reshape(2, 5)

array([[0.52437456, 0.15627745, 0.64844722, 0.75311509, 0.31688766],
       [0.58833333, 0.26713973, 0.09648144, 0.6677006 , 0.73264939]])

### 2.3 Random a sample from a given dataset
#### 2.3.1 Random from **1d array** dataset

In [9]:
int_ds = np.arange(0, 150, 3)
int_ds

array([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
        39,  42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,
        78,  81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114,
       117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147])

In [10]:
rng.choice(int_ds, size = 10)

array([ 69,  33,  84,  39,  72,  45,  72, 141,  33,  24])

In [11]:
rng.choice(int_ds, size = (5, 2))

array([[ 90, 126],
       [ 45,   0],
       [ 69,  24],
       [ 96,  18],
       [105, 141]])

#### 2.3.2 Random from **2d array** dataset

In [12]:
int_ds2 = int_ds.reshape(5, 10)
int_ds2

array([[  0,   3,   6,   9,  12,  15,  18,  21,  24,  27],
       [ 30,  33,  36,  39,  42,  45,  48,  51,  54,  57],
       [ 60,  63,  66,  69,  72,  75,  78,  81,  84,  87],
       [ 90,  93,  96,  99, 102, 105, 108, 111, 114, 117],
       [120, 123, 126, 129, 132, 135, 138, 141, 144, 147]])

##### 2.3.2.1 Random along axis=0 (row), but select all columns of the sampled rows

In [13]:
x = rng.choice(int_ds2, size = (2,), axis = 0)
print(x)
print('x.shape:', x.shape)

[[60 63 66 69 72 75 78 81 84 87]
 [ 0  3  6  9 12 15 18 21 24 27]]
x.shape: (2, 10)


##### 2.3.2.2 Random along axis=1 (column), but select all rows of the sampled columns

In [14]:
x = rng.choice(int_ds2, size = (2,), axis = 1)
print(x)
print('x.shape:', x.shape)

[[  3  21]
 [ 33  51]
 [ 63  81]
 [ 93 111]
 [123 141]]
x.shape: (5, 2)


## 3. Permutation

---

### 3.1 Shuffle method
- **Shuffle** the array and update it **in-place** with the shuffled values.

In [15]:
x = np.arange(0, 10)
print(x, '\n')

rng = default_rng()
rng.shuffle(x)
print(x)

[0 1 2 3 4 5 6 7 8 9] 

[9 7 4 6 2 1 3 0 8 5]


In [16]:
x = np.arange(0, 12).reshape(3, 4)
print(x, '\n')

rng = default_rng()
rng.shuffle(x, axis = 0)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]


In [17]:
x = np.arange(0, 12).reshape(3, 4)
print(x, '\n')

rng = default_rng()
rng.shuffle(x, axis = 1)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 1  3  2  0]
 [ 5  7  6  4]
 [ 9 11 10  8]]


### 3.2 Permuted method
• Use **permuted()** method - create a **new shuffled array**

In [18]:
x = np.arange(0, 10)
print(x, '\n')

rng = default_rng()
pm = rng.permuted(x)
print(pm, x is pm)

[0 1 2 3 4 5 6 7 8 9] 

[7 1 9 5 4 6 0 8 3 2] False
