# 0. Understand **NumPy Array**
---

## 0.1 Install **NumPy**

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


## 0.2 **NumPy** vs **List**

In [2]:
import numpy as np
size = 500000
x = np.arange(0, size)
y = np.arange(0, size)

# Magic command
%timeit -n5 x * y

1.32 ms ± 209 µs per loop (mean ± std. dev. of 7 runs, 5 loops each)


In [3]:
lx = list(range(0, size))
ly = list(range(0, size))

# List comprehension
print('[lx[i] * ly[i] for i in range(0, size)]')
%timeit -n5 [lx[i] * ly[i] for i in range(0, size)]

[lx[i] * ly[i] for i in range(0, size)]
82 ms ± 7.3 ms per loop (mean ± std. dev. of 7 runs, 5 loops each)


In [4]:
# Map 
print('list(map(lambda x, y: x * y, lx, ly))')
%timeit -n5 list(map(lambda x, y: x * y, lx, ly))

list(map(lambda x, y: x * y, lx, ly))
69.9 ms ± 6.04 ms per loop (mean ± std. dev. of 7 runs, 5 loops each)


# 1. Understand **NumPy Array (ndarray)**
---

## 1.1 NumPy `ndarray` Structure

In [5]:
import numpy as np
x = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(x)
print('dtype =', x.dtype)
print('item size =', x.dtype.itemsize)
print('item x[0] =', x[0])
print('type of item x[0] =', type(x[0]))

[10 20 30 40 50 60 70 80]
dtype = int32
item size = 4
item x[0] = 10
type of item x[0] = <class 'numpy.int32'>


## 1.2 Data Type Object (dtype)
### 1.2.1 <u>Specify `dtype`</u> for specific array scalar type

In [6]:
x = np.array([10, 20, 30, 40, 50, 60, 70, 80], np.float64)
print(x)
print('dtype =', x.dtype)
print('item size =', x.dtype.itemsize)
print('item x[0] =', x[0])
print('type of item x[0] =', type(x[0]))

[10. 20. 30. 40. 50. 60. 70. 80.]
dtype = float64
item size = 8
item x[0] = 10.0
type of item x[0] = <class 'numpy.float64'>


### 1.2.2 Define <u>structure</u> dtype

In [7]:
# Define customer structure dtype
customer_dtype = np.dtype([('cid', np.str_, 10), ('name', str, 30), ('age', np.int8)])

# Customer records
customer_list = [('C100', 'David', 25), ('C200', 'Phil', 30), ('C300', 'Steve', 35)]

# Create customer_dtype ndarray
customers = np.array(customer_list, dtype = customer_dtype)

print(customers)
print(customers[0])
print(customers['name'])
print(customers[customers['age'] > 30])

[('C100', 'David', 25) ('C200', 'Phil', 30) ('C300', 'Steve', 35)]
('C100', 'David', 25)
['David' 'Phil' 'Steve']
[('C300', 'Steve', 35)]


# 2. Create **n-dimentional array**
---

## 2.1 Use `numpy.array()`

- Create **1-D array** using `np.array()` or `np.arange()`.

In [8]:
x = np.arange(1, 13)
print(x)
print(x.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


- `ndarray.reshape()`

In [9]:
rx = x.reshape(3, 4)
print(x)
print(rx)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


- **View** vs **copy**.

In [10]:
# Data object is still only x
# If you change x, rx changes
# Because rx is the view of x 
x[0] = 100
print(x)
print(rx)

[100   2   3   4   5   6   7   8   9  10  11  12]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [11]:
rx.base

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [12]:
# Copy of x
x[0] = 1
rcx = x.reshape(3, 4).copy()
x[0] = 100
print(x)
print(rx)
print(rcx)

[100   2   3   4   5   6   7   8   9  10  11  12]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


- **Row-major** vs **column-major** order.

In [13]:
# order = 'C' => Row-major order
x = np.array(range(1, 13)).reshape(3, 4, order = 'C')
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
# order = 'F' => Column-major order
x = np.array(range(1, 13)).reshape(3, 4, order = 'F')
print(x)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


- Create **2-D array** using `np.array()`

In [15]:
x = np.array([ [1, 2, 3], [4, 5, 6] ])
print(x.shape)

(2, 3)


- Working with *axis*

In [16]:
print(x, '\n')
# axis = 0 => All row in vertical direction
print('np.sum(x, axis = 0) = ', np.sum(x, axis = 0))

# axis = 1 => All column in horizontal direction
print('np.sum(x, axis = 1) = ', np.sum(x, axis = 1))

[[1 2 3]
 [4 5 6]] 

np.sum(x, axis = 0) =  [5 7 9]
np.sum(x, axis = 1) =  [ 6 15]


- Create **3-D array** using `np.array()`

In [17]:
x = np.array([ [ [1, 2, 3], [4, 5, 6] ], [ [7, 8, 9], [10, 11, 12] ] ])
print(x)
print(x.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


- Create **ndarray** of *objects*

In [18]:
x = np.array([ [1, 2, 3], [4, 5, 6], [7, 8] ])
# Cannot create array with different lengths
# We need to create object instead

C:\Users\tatas\AppData\Local\Temp\ipykernel_7212\1077699327.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x = np.array([ [1, 2, 3], [4, 5, 6], [7, 8] ])


In [19]:
x = np.array([ [1, 2, 3], [4, 5, 6], [7, 8] ], dtype='object')
print(x)
print(x.shape)
print(x[0], type(x[0]))

[list([1, 2, 3]) list([4, 5, 6]) list([7, 8])]
(3,)
[1, 2, 3] <class 'list'>


## 2.2 Use `numpy.arange()` 
- Create an array using `numpy.arange()` based on the specified `start`, `stop`, and `step` values.

In [20]:
x = np.arange(10, 90, 10, np.float64)
print(x)
print(x.shape)

[10. 20. 30. 40. 50. 60. 70. 80.]
(8,)


## 2.3 Use `numpy.empty()`, `numpy.zeros()`, `numpy.ones()`
    numpy.empty(shape, dtype = float, order = 'C')
- Create an uninitialized array (create with whatever values in the allocated memory of `ndarray`)

In [21]:
m = np.empty((3, 2), dtype = int)
print(m)

[[845727872       368]
 [845726784       368]
 [845726656       368]]


In [22]:
m = np.zeros((3, 2), dtype = int)
print(m)

[[0 0]
 [0 0]
 [0 0]]


In [23]:
m = np.ones((3, 2), dtype = int)
print(m)

[[1 1]
 [1 1]
 [1 1]]


# 3. **Indexing** and **Slicing** Array
---

## 3.1 Understand array indexing

In [24]:
x = np.arange(0, 12).reshape(4, 3)
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


- Access **a specific item** in an array.

In [25]:
print(x[0, 2])
x[0, 2] = -9
print(x)

2
[[ 0  1 -9]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


- Access **an entire row**

In [26]:
print(x[1])

# Update all items in row 1
x[1] = 8 
print(x)

[3 4 5]
[[ 0  1 -9]
 [ 8  8  8]
 [ 6  7  8]
 [ 9 10 11]]


- Access **an entire column**

In [27]:
# Get all rows
# And all columns except last column
print(x[:, 0:2])

[[ 0  1]
 [ 8  8]
 [ 6  7]
 [ 9 10]]


## 3.2 Understand array slicing
**<u>Note:</u>** The sliced array is a **view** of the original array.

### 3.2.1 Slicing with `[start: stop: step]`
- Similar to the way of indexing list works
- **<u>Notice</u>** that the difference between slicing and direct indexing on specific item

In [28]:
x = np.arange(0, 20).reshape(4, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [29]:
# Get from row 1 to last
print(x[1:])

# Get from row 1 to 2
print(x[1:3])

# Get from row 0 to last step by 2
print(x[0::2])

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]]


In [30]:
print(x[-3:])

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [31]:
print(x[:-3])

[[0 1 2 3 4]]


### 3.2.2 Slicing 3-D array

In [32]:
x = np.arange(0, 12).reshape(2, 3, 2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [33]:
x[0, 0:2,]

array([[0, 1],
       [2, 3]])

## 3.3 Advanced Indexing
- Use **Integer Indexing** to select arbitrary items in each dimentions

In [34]:
x = np.arange(0, 20).reshape(4, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [35]:
x[ [0, 1] ]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
# (row, column)
# (0, 1) and (1, 3)
x[ [0, 1], [1, 3] ]

array([1, 8])

In [37]:
x[ [[1, 1], [3, 3]], [[1, 2], [1, 2]] ]

array([[ 6,  7],
       [16, 17]])

- Use **Boolean Indexing** to select arbitrary items in each dimentions

- Use **Boolean as Masking index** to select specific elements based on certain criteria